#!/usr/bin/php
<?PHP
require_once "/usr/local/emhttp/webGui/include/publish.php";
function emhttp_command($cmd)
{
    $var = parse_ini_file("/var/local/emhttp/var.ini");
    $cmd .= "&csrf_token={$var['csrf_token']}";
    return curl_socket("/var/run/emhttpd.socket", "http://localhost/update", $cmd);
}
$result = emhttp_command($argv[1]);
if ($result === "") exit(0);
echo "$result".PHP_EOL;
exit(1);
?>
