#!/bin/bash
# daemonize the 'diskload' script
DAEMON="/usr/local/emhttp/webGui/scripts/diskload"
if [[ "$(pgrep -f $DAEMON)" == "" ]]; then
  logger "Starting $(basename $DAEMON)"
  $DAEMON &>/dev/null &
fi
